version: 2
jobs:
  build:
    docker:
      - image: node:8.9-alpine

    steps:
      - checkout

      - run:
          name: install
          command: npm install
      - run:
          name: tests
          command: npm run test

      - run:
          name: Print the Current Time
          command: date
